import type { Product, ProductSlug } from "./types";

export const products: Product[] = [
  {
    slug: "xerox-buddy",
    name: "Xerox Buddy",
    icon: "printer",
    status: "Live",
    seo: {
      title: "Xerox Buddy | QR Self-Service Printing for Print Shops",
      description:
        "Xerox Buddy lets customers scan a QR or tap an NFC standee, upload a PDF, image or Word file and print at your shop. No pen drives, no counter rush.",
      keywords: "self-service printing software, xerox shop software, print from QR code, stationery shop printing",
    },
    h1: "Xerox Buddy: let customers send files straight to your printer",
    hero: "At rush hour, you have no time to download PDFs from your computer and press print. With Xerox Buddy, customers scan or tap a standee, upload their file and the print job reaches your printer. You collect the pages and the payment.",
    card: "Customers scan a standee, upload a file and print at your shop, so the counter never jams at rush hour.",
    problem:
      "Most print jobs at a stationery shop are simple: A4 pages, black and white or color. Yet each one still means asking for a file, finding it, downloading it and printing it. When the queue grows, the counter slows down and customers wait.",
    how: [
      {
        heading: "How it works for your customer",
        steps: true,
        items: [
          "Scan the QR code or tap the NFC standee at your counter. The Xerox Buddy website opens.",
          "Upload a PDF, image or Word document.",
          "Choose the print options. [Confirm options shown: black and white or color, copies, page range.]",
          "The file goes to your printer. Your customer collects the pages and pays you at the counter.",
        ],
      },
      {
        heading: "How it works for you",
        intro: "Your shop gets a dashboard on your desktop. Every upload appears as an entry, and you decide who presses print.",
        items: [
          "Customer prints: the customer's upload prints automatically on your connected printer.",
          "You print: each entry shows a print button beside it, and the job prints only when you press it.",
          "Change the setting any time as your shop gets busy or quiet.",
          "Our desktop app connects your printing device to the website for automatic printing.",
          "Track every print job from your dashboard.",
        ],
      },
    ],
    featuresHeading: "Features",
    features: [
      "Scan or tap standee for your counter",
      "Upload PDF, images and Word documents",
      "Automatic printing through a connected printer",
      "Shop dashboard on desktop with settings and a live list of entries",
      "Choose who prints: the customer or you",
      "No app download for customers",
      "Print job tracking",
    ],
    who: "Stationery shops, xerox and photocopy shops, cyber cafes and campus print counters. [Confirm the list.]",
    faq: [
      { q: "Do my customers need to install an app?", a: "No. They scan or tap, and the website opens in their phone browser." },
      { q: "Which files can customers upload?", a: "PDF, images and Word documents." },
      { q: "Can I stop customers from printing on their own?", a: "Yes. Switch to the mode where you press the print button beside each entry." },
      { q: "Who collects payment?", a: "You do. The customer pays you at the counter when collecting the pages." },
      { q: "Will it work with my printer?", a: "It connects to your printing device through our desktop app. [Confirm supported printers and operating systems.]" },
    ],
    cta: { heading: "Bring Xerox Buddy to your shop.", sub: "Request a demo or write to contact@priinteve.com.", button: "Request a demo" },
    related: "vantadot",
    mock: { title: "Shop dashboard", rows: [["Assignment.pdf", "Printing"], ["ID-photo.jpg", "Queued"], ["Notes.docx", "Ready"]] },
    builtFor: "Stationery, xerox and print shops",
    howCustomersUse: "Scan or tap a standee, upload a file, collect the printout",
  },
  {
    slug: "vantadot",
    name: "Vantadot",
    icon: "utensils",
    status: "Live",
    seo: {
      title: "Vantadot | QR Table Ordering & Restaurant Order System",
      description:
        "Vantadot is a restaurant ordering system with QR and NFC table standees, takeaway ordering, kitchen display screens and one dashboard to run it all.",
      keywords: "QR code restaurant ordering system, table ordering system, restaurant order management software, kitchen display",
    },
    h1: "Vantadot: restaurant order management with ordering at the table",
    hero: "Put a small standee on every table. Guests scan or tap, browse your menu and order. Every order lands in one dashboard, your chefs see it on a TV, and your guests see when it is ready.",
    card: "Customers order from the table by scan or tap. Your kitchen and your dashboard see it instantly.",
    how: [
      {
        heading: "How it works",
        steps: true,
        items: [
          "Every table has its own standee. Guests scan the QR code or tap the NFC tag to open your branded menu and place an order from their seat.",
          "One standee at the reception counter handles takeaway orders.",
          "All orders from all tables and takeaway arrive in a single dashboard.",
          "A kitchen TV shows chefs what to cook. A customer-facing TV shows which orders are ready.",
          "Track orders and payments from the dashboard.",
        ],
      },
    ],
    featuresHeading: "What you get",
    features: [
      "Table-wise QR and NFC standees",
      "Takeaway ordering from the reception standee",
      "One dashboard for orders and payments",
      "TV screens for the kitchen and for customers",
      "Website, desktop apps and Android TV app",
      "Your own branded menu",
      "Pickup screen with Indian regional settings",
      "A digital business card for your restaurant",
      "Built for many restaurants and branches on one platform",
    ],
    comingSoon: "Delivery-app integration, WhatsApp billing, and loyalty and inventory management across branches.",
    who: "Restaurants, cafes, food courts and food businesses with several tables or branches.",
    faq: [
      { q: "Do guests need to download an app?", a: "No. They scan or tap the standee and order in the browser." },
      { q: "Can I manage takeaway orders too?", a: "Yes. A standee at the reception counter takes takeaway orders into the same dashboard." },
      { q: "How do chefs see orders?", a: "On a kitchen TV that shows incoming orders. A separate screen shows customers when their order is ready." },
      { q: "What devices does it run on?", a: "Website, desktop apps and an Android TV app." },
      { q: "Can I run more than one restaurant?", a: "Yes. Vantadot is built as one platform for many restaurants, each with its own menu." },
    ],
    cta: { heading: "See Vantadot in your restaurant.", button: "Request a demo" },
    related: "salony",
    mock: { title: "Live orders", rows: [["Table 4 · 2 items", "New"], ["Takeaway #18", "Cooking"], ["Table 7", "Ready"]] },
    builtFor: "Restaurants and food businesses",
    howCustomersUse: "Scan or tap the table standee and order",
  },
  {
    slug: "salony",
    name: "Salony",
    icon: "scissors",
    status: "Live",
    seo: {
      title: "Salony | Salon, Barber & Spa Appointment Booking Software",
      description:
        "Salony lets customers book salon, barbershop and spa appointments online, while you manage every booking from one simple dashboard.",
      keywords: "salon appointment booking software, barber shop booking app, spa booking system, salon management software",
    },
    h1: "Salony: appointment booking for salons, barbershops and spas",
    hero: "Let customers book their slot online, and keep your day organised from one dashboard. Salony is made for professional salons, barbershops and spas that want a smooth front desk.",
    card: "Let customers book salon, barbershop and spa appointments online and manage every booking in one place.",
    how: [
      {
        heading: "How it works",
        steps: true,
        items: [
          "Your customer opens your booking page from a link, QR code or NFC tap and chooses a service and a time.",
          "The appointment appears in your salon dashboard.",
          "You manage entries from one place.",
        ],
      },
    ],
    featuresHeading: "Features",
    features: [
      "Online appointment booking for customers",
      "Dashboard to manage all appointments",
      "Built for salons, barbershops and spas",
      "No app download for customers",
    ],
    featuresNote: "[Confirm and add: staff and service setup, reminders, payments, customer history, multi-branch support. List only what is live today.]",
    who: "Hair salons, unisex salons, barbershops, beauty parlours and spas.",
    faq: [
      { q: "Do customers need an app to book?", a: "No. They book from your booking page in their phone browser." },
      { q: "Where do I see my appointments?", a: "In the Salony dashboard." },
      { q: "Is it only for large salons?", a: "No. It suits any salon, barbershop or spa that takes appointments." },
    ],
    cta: { heading: "Fill your appointment book.", button: "Request a demo" },
    related: "nectcard",
    mock: { title: "Today's appointments", rows: [["Haircut · 11:00", "Booked"], ["Spa · 12:30", "Booked"], ["Beard trim · 2:00", "New"]] },
    builtFor: "Salons, barbershops and spas",
    howCustomersUse: "Book an appointment online",
  },
  {
    slug: "nectcard",
    name: "Nectcard",
    icon: "card",
    status: "Live",
    seo: {
      title: "Nectcard | NFC Digital Business Card for India",
      description:
        "Create a digital business card shared by NFC tap or QR scan. Add contacts, social links, a gallery and brochure, and see how many people view it.",
      keywords: "NFC digital business card, digital visiting card India, QR business card, NFC visiting card",
    },
    h1: "Nectcard: your business card, one tap away",
    hero: "A digital business card that opens a full profile when someone taps your NFC card or scans your QR code. Save details to their contacts, see your work, reach you on WhatsApp.",
    card: "One digital business card that opens a full profile with a tap or a scan.",
    heroButton: { label: "Create your card", href: "https://cards.priinteve.com", secondary: "Talk to us" },
    how: [
      {
        heading: "How it works",
        steps: true,
        items: [
          "Build your card in a guided setup and add your brand colors.",
          "Pick the fields you want: phone, email, website, social links, WhatsApp, address and a PDF brochure.",
          "Show your work in a gallery of images and YouTube videos.",
          "Share through an NFC card or a printable QR code.",
          "Watch views on your dashboard.",
        ],
      },
    ],
    featuresHeading: "Features",
    features: [
      "Guided card builder with your brand colors",
      "Field library: phone, email, website, social links, WhatsApp, address, PDF brochure",
      "Gallery with images and YouTube videos",
      "Save to contacts in one tap",
      "NFC card and printable QR code",
      "View counts on your dashboard",
      "Referral program: earn wallet credit when someone you refer buys",
    ],
    who: "Shops, studios, professionals and teams that want a modern digital identity.",
    faq: [
      { q: "Does the person receiving my card need an app?", a: "No. The card opens as a web page after a tap or scan." },
      { q: "Can people save my number?", a: "Yes. Visitors can save your details straight to their contacts." },
      { q: "Can I see who views my card?", a: "You can see how many people view it from your dashboard." },
      { q: "How does the referral program work?", a: "You earn wallet credit when someone you refer buys." },
      { q: "Can I get a physical NFC card?", a: "Yes. [Confirm physical card options and plan details before publishing.]" },
    ],
    cta: { heading: "Create your Nectcard today.", button: "Create your card", href: "https://cards.priinteve.com" },
    related: "xerox-buddy",
    mock: { title: "Your Nectcard", rows: [["Your name · Role", "NFC"], ["Save to contacts", "Tap"], ["Card views", "—"]] },
    builtFor: "Professionals, shops and teams",
    howCustomersUse: "Tap or scan to open a full digital profile",
  },
  {
    slug: "priinteve-printing",
    name: "Priinteve Printing",
    icon: "package",
    status: "Coming soon",
    seo: {
      title: "Priinteve Printing | Custom On-Demand Printing in India",
      description:
        "Upload your design, order custom print online and get it delivered. Priinteve Printing is coming soon with vetted local printers and order tracking.",
      keywords: "custom printing online India, on-demand printing, bulk printing, business printing delivered",
    },
    h1: "Priinteve Printing: print any thing, anywhere, on demand",
    hero: "Choose what you want to print, upload your design and place your order on web or mobile. Vetted local printers produce it and we deliver it to you.",
    card: "Custom print, produced by vetted local printers and delivered to you.",
    heroButton: { label: "Join the waitlist", href: "#waitlist" },
    how: [
      {
        heading: "How it will work",
        steps: true,
        items: [
          "Choose what you want to print.",
          "Upload your design.",
          "Place your order on web or mobile.",
          "A vetted local printer produces your order.",
          "Track the order until it is delivered.",
        ],
      },
    ],
    featuresHeading: "Why it is different",
    features: [
      "One brand, one experience, whichever printer makes your order.",
      "Vetted local printers, so quality stays consistent.",
      "Made for businesses that need real quantities: 25 to 1,000 pieces per order.",
      "Order tracking from placement to delivery.",
    ],
    waitlistFields: ["Name", "Phone", "Email", "What you want to print", "Usual quantity"],
    faq: [
      { q: "When does it launch?", a: "We are preparing the launch. Join the waitlist and we will tell you first. [Add date if known.]" },
      { q: "What quantities can I order?", a: "From 25 to 1,000 pieces per order." },
      { q: "Who prints my order?", a: "A vetted local printer, under one consistent Priinteve experience." },
      { q: "Can I print one piece today?", a: "Not yet. For single-page printing at a shop, see Xerox Buddy." },
    ],
    cta: { heading: "Join the waitlist.", sub: "We will tell you first when we launch.", button: "Join the waitlist", href: "#waitlist" },
    related: "xerox-buddy",
    mock: { title: "Order tracking", rows: [["Upload your design", "Step 1"], ["Local printer produces", "Step 2"], ["Delivered to you", "Step 3"]] },
    builtFor: "Businesses and individuals needing print",
    howCustomersUse: "Upload a design, order, get it delivered",
  },
];

export const productBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const getProduct = (slug: ProductSlug) => products.find((p) => p.slug === slug)!;
